---
application:
  name: "squizer-backend"
  project: "squizer-backend"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "squizer_db"
  version: "4.4"
routers:
- name: "main-squizer-backend"
  routes:
  - application_name: "squizer-backend"
    paths:
    - "/*"
